# Docker Compose override for development
# This file provides development-specific configurations

version: '3.8'

services:
  webapp:
    # Override for development - use local code mounting and hot reload
    command: ["python3", "-m", "uvicorn", "src.realtor_buddy.webapp.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=debug
    volumes:
      - ./src:/app/src
      - ./requirements.txt:/app/requirements.txt
      - model_cache:/root/.cache/huggingface
    
  # Optional: Add nginx reverse proxy for production-like testing
  nginx:
    image: nginx:alpine
    container_name: realtor-buddy-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - webapp
    restart: unless-stopped
    profiles:
      - production